"""empty message

Revision ID: 506893658c9a
Revises: e03551f7cb25
Create Date: 2019-03-24 15:30:41.961961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506893658c9a'
down_revision = 'e03551f7cb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chemStation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('greenHouse', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jewel', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('jewel')
        batch_op.drop_column('greenHouse')
        batch_op.drop_column('chemStation')

    # ### end Alembic commands ###
