"""empty message

Revision ID: 814697ac04d4
Revises: f78659aaa2a2
Create Date: 2019-03-07 17:07:11.043934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814697ac04d4'
down_revision = 'f78659aaa2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rockbiteId', sa.String(length=32), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_guild_rockbiteId'), ['rockbiteId'])
        batch_op.drop_constraint('uq_guild_rockbiteID', type_='unique')
        batch_op.drop_column('rockbiteID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rockbiteID', sa.VARCHAR(length=32), nullable=False))
        batch_op.create_unique_constraint('uq_guild_rockbiteID', ['rockbiteID'])
        batch_op.drop_constraint(batch_op.f('uq_guild_rockbiteId'), type_='unique')
        batch_op.drop_column('rockbiteId')

    # ### end Alembic commands ###
