"""empty message

Revision ID: 89e1dab5c281
Revises: 506893658c9a
Create Date: 2019-04-27 17:46:12.751762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e1dab5c281'
down_revision = '506893658c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_constraint('uq_guild_rockbiteId', type_='unique')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
        batch_op.drop_constraint('uq_player_rockbiteId', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_player_rockbiteId', ['rockbiteId'])
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_guild_rockbiteId', ['rockbiteId'])
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
