"""empty message

Revision ID: a5636f60c769
Revises: 142812d6663e
Create Date: 2019-05-10 17:58:13.283729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5636f60c769'
down_revision = '142812d6663e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)

    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.alter_column('rockbiteId',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
