"""empty message

Revision ID: e03551f7cb25
Revises: 
Create Date: 2019-03-09 19:22:12.795813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03551f7cb25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('rockbiteId', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('lastVisited', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild')),
    sa.UniqueConstraint('rockbiteId', name=op.f('uq_guild_rockbiteId'))
    )
    op.create_table('player',
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('rockbiteId', sa.String(length=24), nullable=False),
    sa.Column('lastOnline', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('mine', sa.Integer(), nullable=True),
    sa.Column('chemMine', sa.Integer(), nullable=True),
    sa.Column('oil', sa.Integer(), nullable=True),
    sa.Column('crafters', sa.Integer(), nullable=True),
    sa.Column('smelters', sa.Integer(), nullable=True),
    sa.Column('lastEventDonation', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name=op.f('fk_player_guild_id_guild')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('rockbiteId', name=op.f('uq_player_rockbiteId'))
    )
    op.create_table('timestamp',
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name=op.f('fk_timestamp_guild_id_guild')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timestamp'))
    )
    op.create_table('count',
    sa.Column('timestamp_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('donated', sa.BigInteger(), nullable=True),
    sa.Column('received', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_count_player_id_player')),
    sa.ForeignKeyConstraint(['timestamp_id'], ['timestamp.id'], name=op.f('fk_count_timestamp_id_timestamp')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_count'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count')
    op.drop_table('timestamp')
    op.drop_table('player')
    op.drop_table('guild')
    # ### end Alembic commands ###
