"""empty message

Revision ID: f78659aaa2a2
Revises: 422c9b1a7599
Create Date: 2019-03-06 23:43:15.803643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78659aaa2a2'
down_revision = '422c9b1a7599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.drop_column('totalDonations')
        batch_op.drop_column('totalLevel')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rockbiteId', sa.String(length=24), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_player_rockbiteId'), ['rockbiteId'])
        batch_op.drop_column('rockbiteID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rockbiteID', sa.VARCHAR(length=24), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_player_rockbiteId'), type_='unique')
        batch_op.drop_column('rockbiteId')

    with op.batch_alter_table('guild', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalLevel', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('totalDonations', sa.BIGINT(), nullable=True))

    # ### end Alembic commands ###
